#!/usr/bin/env ruby
# encoding: utf-8

require 'wordnet'
require 'indefinite_article'
require 'twitter'
require 'linguistics'

require './config.rb'

$lexicon = WordNet::Lexicon.new
Linguistics.use( :en )

$letters = [*'a'..'z'] + ([*'a'..'z'].select { |x| x =~ /[^qxjyvzw]/ }) * 6
$consonants = $letters.select { |x| x =~ /[^aeiou]/ }
$vowels = $letters.select { |x| x =~ /[aeiouy]/ }

def next_letter(previous)
  if $consonants.include?(previous)
    ($consonants + $vowels * 100).sample
  else
    ($vowels + $consonants * 5).sample
  end
end

def name
  length = 2 + rand(8)
  name = $letters.sample
  until name.length == length do
    name += next_letter(name[-1, 1])
  end
  lastCapitalized = -3
  for i in 0..(name.length - 2)
    if (lastCapitalized + 2 < i) && (i == 0 || rand(8) == 1)
      name[i] = name[i].capitalize
      lastCapitalized = i
    end
  end
  if rand(4) == 1
    name += ['.ly', '.io', 'Box', 'App'].sample
  end
  name
end

def adjective
  adj = WordNet::Synset.adjectives.order(Sequel.lit('RANDOM()')).limit(1).all[0].words[0].lemma
  if (rand(4) == 1)
    adverb = WordNet::Synset.adverbs.order(Sequel.lit('RANDOM()')).limit(1).all[0].words[0].lemma
    "#{adverb} #{adj}"
  else
    adj
  end
end

def noun
  WordNet::Synset.nouns.order(Sequel.lit('RANDOM()')).limit(1).all[0].words[0].lemma
end

def verb
  verb = ['written', 'created', 'crafted', 'conjured', 'incanted'].sample
  if (rand(10) == 1)
    adverb = WordNet::Synset.adverbs.order(Sequel.lit('RANDOM()')).limit(1).all[0].words[0].lemma
    "#{adverb} #{verb}"
  else
    verb
  end
end

def lang
  File.readlines("langs.txt").sample.strip
end

idea = "Show HN: #{name} — #{adjective.indefinitize} #{noun}, #{verb} in #{lang}."

if ARGV[0] == 'post'
  twitter = Twitter::REST::Client.new do |config|
    config.consumer_key        = HnIdeatorConfig::CONSUMER_KEY
    config.consumer_secret     = HnIdeatorConfig::CONSUMER_SECRET
    config.access_token        = HnIdeatorConfig::ACCESS_TOKEN
    config.access_token_secret = HnIdeatorConfig::ACCESS_TOKEN_SECRET
  end
  twitter.update(idea)
else
  puts idea
end
